/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetsupermarchergraphique;

import ClassMetier.Employe;
import ClassMetier.Rayon;
import ClassMetier.Secteur;
import ClassMetier.Travailler;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jerem
 */
public class frmPrincipal extends javax.swing.JFrame {
ArrayList<Secteur>mesSecteurs=new ArrayList<>();
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomEmploye = new javax.swing.JTextField();
        txtTempsMoy = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTempsTotEmploye = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Projet supermarché");

        tblInfos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom du secteur ", "Numero du secteur", "Numero rayon", "Nom du rayon", "Numero de l'employé", "Nom de l'employé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInfos);

        jLabel2.setText("Temps de travaille d'un employé");

        jLabel3.setText("Temps moyen");

        btnRechercher.setText("Rechercher");
        btnRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechercherMouseClicked(evt);
            }
        });

        jLabel4.setText("Temps total employé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNomEmploye))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(txtTempsMoy))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(txtTempsTotEmploye))))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempsMoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempsTotEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRechercher)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel dtmInfos=new DefaultTableModel();
        dtmInfos=(DefaultTableModel) tblInfos.getModel();
        Vector v;
        
        
        
        Secteur sec1=new Secteur(1,"Multimedia");
        Secteur sec2=new Secteur(2,"Electromenager");
        
        Rayon ray1=new Rayon(1, "Télévision");
        Rayon ray2=new Rayon(2, "Informatique");
        Rayon ray3=new Rayon(3, "Lave-vaisselle");
        
        Employe emp1=new Employe(1, "Marie");
        Employe emp2=new Employe(2, "Stéphanie");
        Employe emp3=new Employe(3, "Karim");
        Employe emp4=new Employe(4, "Pierre");
        Employe emp5=new Employe(5, "Lucille");
        
        Travailler trav1=new Travailler(emp1, 4);
        Travailler trav2=new Travailler(emp2, 8);
        Travailler trav3=new Travailler(emp3, 1);
        Travailler trav4=new Travailler(emp4, 5);
        Travailler trav5=new Travailler(emp5, 6);
        Travailler trav6=new Travailler(emp1, 8);
        Travailler trav7=new Travailler(emp2, 3);
        
        //Ca signifife que pr le rayon Télévision
        //l'employé Marie a travaillé 4h
        ray1.getLesTravailler().add(trav1);
        ray1.getLesTravailler().add(trav2);
        ray2.getLesTravailler().add(trav3);
        ray2.getLesTravailler().add(trav4);
        ray3.getLesTravailler().add(trav5);
        ray3.getLesTravailler().add(trav6);
        ray3.getLesTravailler().add(trav7);
        
        sec1.getLesRayons().add(ray1);
        sec1.getLesRayons().add(ray2);
        sec2.getLesRayons().add(ray3);
        
        
        
        mesSecteurs.add(sec1);
        mesSecteurs.add(sec2);
        
        int tempsTot = 0;
        int nbEmploye=0;
        for(Secteur sec:mesSecteurs)
        {
            for(Rayon ray:sec.getLesRayons())
            {
                for(Travailler trav:ray.getLesTravailler())
                {
                    nbEmploye++;
                    tempsTot+=trav.getTempsPasse();
                    v=new Vector();
                    v.add(sec.getIdSecteur());
                    v.add(sec.getNomSecteur());
                    v.add(ray.getIdRayon());
                    v.add(ray.getNomRayon());
                    v.add(trav.getUnEmploye().getIdEmploye());
                    v.add(trav.getUnEmploye().getNomEmploye());
                    dtmInfos.addRow(v);
                }
            }
        }
        
        txtTempsMoy.setText(String.valueOf(tempsTot/nbEmploye));
    }//GEN-LAST:event_formWindowOpened

    private void btnRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechercherMouseClicked
        // TODO add your handling code here:

        if(txtNomEmploye.getText().compareTo("")==0){
            JOptionPane.showMessageDialog(this, "Veuillez saisir le nom de l'employer");
        }
        else{
            String nomMinuscule=txtNomEmploye.getText().toLowerCase();
            String nomOk = nomMinuscule.substring(0, 1).toUpperCase()+nomMinuscule.substring(1);
            JOptionPane.showMessageDialog(this, nomOk);
        }
        
        int nbFois=0;
        int tempsTot=0;
        for(Secteur sec:mesSecteurs)
        {
            for(Rayon ray:sec.getLesRayons())
            {
                for(Travailler trav:ray.getLesTravailler())
                {
                    String nomOk = null;
                    if(trav.getUnEmploye().getNomEmploye().compareTo(nomOk)==0)
                    {
                        tempsTot+=trav.getTempsPasse();
                        nbFois++;
                    }
                }
            }
        }
        txtTempsTotEmploye.setText(String.valueOf((double)tempsTot/nbFois));
    }//GEN-LAST:event_btnRechercherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfos;
    private javax.swing.JTextField txtNomEmploye;
    private javax.swing.JTextField txtTempsMoy;
    private javax.swing.JTextField txtTempsTotEmploye;
    // End of variables declaration//GEN-END:variables
}
